[project]
name = "cv-experiments"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "mediapipe>=0.10.32",
    "moviepy<2",
    "numpy>=2.2.6",
    "opencv-python>=4.13.0.92",
]
